version: '3.8'
services:
  flask1:
    build: .
    networks:
      - internal
  flask2:
    build: .
    networks:
      - internal
  flask3:
    build: .
    networks:
      - internal
  nginx:
    image: nginx:latest
    ports:
      - "5000:80"  # Проброс порта 5000 хоста на порт 80 контейнера NGINX
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./keys:/etc/nginx/keys
    networks:
      - internal

networks:
  internal:  # Внутренняя сеть для общения между контейнерам
    driver: bridge
